version: '3'

services:
  web:
    build: .
    command: 
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py loaddata images_api/fixtures/tiers.json &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=hexocean.settings
      - DATABASE_URL=sqlite:///db.sqlite3
      - FIXTURES_PATH=/code/images_api/fixtures/tiers.json
      - SECRET_KEY=${SECRET_KEY}
