# Generated by Django 4.1.6 on 2023-03-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0002_remove_accounttier_max_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accounttier',
            name='original_file_link_presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images_api.accounttier'),
        ),
        migrations.AlterField(
            model_name='accounttier',
            name='generate_expiring_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.DeleteModel(
            name='UserTier',
        ),
        migrations.AddField(
            model_name='imagedimensions',
            name='tier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='images_api.accounttier'),
        ),
        migrations.AddField(
            model_name='image',
            name='dimensions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='images_api.imagedimensions'),
        ),
    ]
