# Generated by Django 4.1.6 on 2023-03-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0003_imagedimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='image',
            name='tier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='images_api.accounttier'),
        ),
        migrations.AlterField(
            model_name='image',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images_api/media/images/'),
        ),
    ]
