# Generated by Django 4.1.6 on 2023-03-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0004_remove_image_dimensions_image_tier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
