# Generated by Django 4.1.6 on 2023-03-07 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0005_image_height_image_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='expiration',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='image',
            name='expiration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
