# Generated by Django 4.1.6 on 2023-03-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0006_rename_expiration_image_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_expireble',
            field=models.BooleanField(default=False),
        ),
    ]
