# Generated by Django 4.1.6 on 2023-03-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0007_image_is_expireble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_expireble',
            new_name='is_expirable',
        ),
    ]
