# Generated by Django 4.1.6 on 2023-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0008_rename_is_expireble_image_is_expirable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tier_type',
        ),
        migrations.AlterField(
            model_name='image',
            name='is_expirable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
