# Generated by Django 4.1.6 on 2023-03-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0009_remove_image_tier_type_alter_image_is_expirable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_expirable',
            field=models.BooleanField(blank=True),
        ),
    ]
