# Generated by Django 4.1.6 on 2023-03-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0016_alter_image_is_expirable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
